sudo: required
language: node_js
node_js:
  - '8'
cache:
  bundler: true
  directories:
    - ~/.npm
    - node_modules
  npm: true
notifications:
  email: false
services:
  - docker
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
  sonarcloud:
    organization: seantrane-github
git:
  depth: false
branches:
  only:
    - master
    - /^release.*$/
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - PATH=$PWD:$PATH
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of some gems
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g github-label-sync lerna typescript
  # - gem install jekyll htmlproofer
install:
  - travis_retry npm install
  # - travis_retry bundle install
stages:
  - test
  - name: deploy
    if: repo = seantrane/monorepo
        AND type != pull_request
        AND branch = master
jobs:
  include:
    - stage: test
      name: 'Checks and Tests'
      script:
        # - npm audit
        - commitlint-travis
        - travis_retry github-label-sync -a "$GH_TOKEN" -l 'https://git.io/fAe5i' seantrane/monorepo
        - npm run ci
        - sonar-scanner
    - stage: deploy
      name: 'Publish and Release'
      script:
        - npm run semantic-release
    # - name: 'Deploy GitHub Pages'
    #   script:
    #     - JEKYLL_GITHUB_TOKEN="$GH_TOKEN" JEKYLL_ENV=production bundle exec jekyll build --destination _site
    #   deploy: &pages
    #     provider: pages
    #     skip-cleanup: true
    #     github-token: "$GH_TOKEN"
    #     # name: Sean Trane
    #     # email: seantrane@users.noreply.github.com
    #     # keep-history: true
    #     target-branch: gh-pages
    #     local-dir: ./_site
    #     on:
    #       repo: seantrane/monorepo
    #       branch: master
