sudo: required
language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - node_modules
  npm: true
notifications:
  email: false
services:
  - docker
addons:
  sonarcloud:
    organization: "seantrane-github"
branches:
  only:
    - master
    - /^greenkeeper.*$/
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - PATH=$PWD:$PATH
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g github-label-sync greenkeeper-lockfile lerna
install:
  - travis_retry npm install
  - lerna bootstrap --hoist
stages:
  - test
  - success
jobs:
  include:
    - stage: test
      name: 'Checks and Tests'
      script:
        - '[[ $TRAVIS_BRANCH =~ ^greenkeeper.*$ ]] && greenkeeper-lockfile-update || exit 0;'
        - npm audit
        - commitlint-travis
        # - lerna run lint
        # - lerna run build
        - travis_retry github-label-sync -a "$GH_TOKEN" -l 'https://git.io/fAe5i' seantrane/monorepo
        # - lerna run test
        # - '[[ $TRAVIS_BRANCH = master ]] && sonar-scanner || exit 0;'
        - '[[ $TRAVIS_BRANCH =~ ^greenkeeper.*$ ]] && greenkeeper-lockfile-upload || exit 0;'
    - stage: success
      name: 'Pull Requests'
      if: type = pull_request
          AND branch = master
      script:
        - 'npx semantic-release-github-pr || exit 0;'
    - name: 'Publish and Release'
      if: repo = seantrane/monorepo
          AND type != pull_request
          AND branch = master
      script:
        - echo "Release is skipped until enabled..."
        # - lerna exec --concurrency 1 "npx --no-install semantic-release -e semantic-release-monorepo"
